version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/data:/prometheus/data
      - ./prometheus/config:/etc/prometheus
    command:
      - '--storage.tsdb.retention.time=7d'
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    cap_drop:
      - all

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager/config:/etc/alertmanager
      - ./alertmanager/data:/alertmanager
    ports:
      - '9093:9093'
    cap_drop:
      - all

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/config/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/config/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - '3000:3000'
    cap_drop:
      - all

  nodeexporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - '9100:9100'
    cap_drop:
      - all
