---
version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/data:/prometheus/data
      - ./prometheus/config:/etc/prometheus
    command:
      - '--web.enable-admin-api'
      - '--storage.tsdb.retention.time=7d'
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    cap_drop:
      - all

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager/config:/etc/alertmanager
      - ./alertmanager/data:/alertmanager
    ports:
      - '9093:9093'
    cap_drop:
      - all

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/config/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/config/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - '3000:3000'
    cap_drop:
      - all

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    command:
      - '--collector.zipkin.host-port=:9411'
      - '--collector.otlp.enabled'
    ports:
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '4317:4317'
      - '4318:4318'
      - '14250:14250'
      - '14268:14268'
      - '14269:14269'
      - '9411:9411'
