{
 "title": "JVM Exporter dashboard",
 "description": "Complete dashboard using metrics from prometheus JMX exporter, with drill down per job > instance",
 "tags": [ "JVM" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "label_values(jvm_info, job)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_info{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"$job\",instance=\"$instance\"} / jvm_memory_bytes_max{area=\"heap\",job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"$job\",instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jvm_info{job=\"$job\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Used {{kubernetes_pod_name}}"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Max {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Used  {{instance}}"
    }
   ]
  },
  {
   "title": "Eden Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=~\".* Eden .*\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Max  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=~\".* Eden .*\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Used  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=~\".* Eden .*\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Committed  {{instance}}"
    }
   ]
  },
  {
   "title": "Old Gen",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=~\".* Old .*\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Max  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=~\".* Old .*\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Used  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=~\".* Old .*\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Committed  {{instance}}"
    }
   ]
  },
  {
   "title": "Survivor Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=~\".* Survivor .*\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Max  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=~\".* Survivor .*\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Used  {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=~\".* Survivor .*\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Committed  {{instance}}"
    }
   ]
  },
  {
   "title": "Metaspace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Metaspace\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Max {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Metaspace\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Used {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Metaspace\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Committed {{instance}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Compressed Class Space\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Max {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Compressed Class Space\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Used {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Compressed Class Space\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Committed {{instance}}"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Code Cache\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Max {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Code Cache\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Used {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Code Cache\",job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "Committed {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "JVM current threads  {{instance}}"
    },
    {
     "expr": "jvm_threads_daemon{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "JVM daemon threads {{instance}}"
    },
    {
     "expr": "jvm_threads_deadlocked{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "JVM deadlocked threads  {{instance}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{job=\"$job\",instance=\"$instance\"}",
     "legendFormat": "{{gc}}  {{instance}}"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"$job\",instance=\"$instance\"}[5m])",
     "legendFormat": "{{gc}} {{instance}}"
    }
   ]
  },
  {
   "title": "Class currently loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_currently_loaded{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "loaded  {{instance}}"
    }
   ]
  }
 ]
}