{
 "title": "Resource pressure",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_uname_info{nodename=\"$name\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(node_uname_info{instance=~\"$node:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{instance=~\"$host:$port\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$host:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"$host:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"$host:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$host:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$host:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$host:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "CPU pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_pressure_cpu_waiting_seconds_total{instance=~\"$host:$port\"}[$__interval])",
     "legendFormat": "Some waiting for CPU"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$host:$port\",job=~\"$job\"} - node_memory_MemFree_bytes{instance=~\"$host:$port\",job=~\"$job\"} - (node_memory_Cached_bytes{instance=~\"$host:$port\",job=~\"$job\"} + node_memory_Buffers_bytes{instance=~\"$host:$port\",job=~\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$host:$port\",job=~\"$job\"} + node_memory_Buffers_bytes{instance=~\"$host:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$host:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$host:$port\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$host:$port\",job=~\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_pressure_memory_waiting_seconds_total{instance=~\"$host:$port\"}[$__interval])",
     "legendFormat": "Some waiting for RAM"
    },
    {
     "expr": "irate(node_pressure_memory_stalled_seconds_total{instance=~\"$host:$port\"}[$__interval])",
     "legendFormat": "All waiting for RAM"
    }
   ]
  },
  {
   "title": "I/O Traffic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$host:$port\",job=~\"$job\"}[5m])*8 + irate(node_network_transmit_bytes_total{instance=~\"$host:$port\",job=~\"$job\"}[5m])*8",
     "legendFormat": "Network - {{device}}"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$host:$port\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])*8 + irate(node_disk_written_bytes_total{instance=~\"$host:$port\",job=~\"$job\",device=~\"[a-z]*[a-z]\"}[5m])*8",
     "legendFormat": "Disk - {{device}}"
    }
   ]
  },
  {
   "title": "I/O pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{instance=~\"$host:$port\"}[$__interval])",
     "legendFormat": "Some waiting for I/O"
    },
    {
     "expr": "irate(node_pressure_io_stalled_seconds_total{instance=~\"$host:$port\"}[$__interval])",
     "legendFormat": "All waiting for I/O"
    }
   ]
  }
 ]
}