---
global:
  scrape_interval: 5s
  evaluation_interval: 60s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
    scheme: http
    timeout: 10s

rule_files:
  - "/etc/prometheus/alerts.yml"

scrape_configs:
  - job_name: 'metrics_collection'
    static_configs:
      - targets: ['nodeexporter:9100']
