global:
  scrape_interval: 30s
  evaluation_interval: 30s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
    scheme: http
    timeout: 10s

rule_files:
  - "/etc/prometheus/alerts.yml"

scrape_configs:
  - job_name: 'node_exporter_test'
    static_configs:
      - targets: ['nodeexporter:9100']
